spring:
  redis:
    database: 5
    host: 127.0.0.1
    password: Perhaps0..
    port: 6379
    timeout: 3s
    jedis:
      pool:
        max-active: 2000
        max-wait: 1s
        max-idle: 500
        min-idle: 50

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Perhaps0..
    url: "jdbc:mysql://122.144.206.146:3306/crm?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false"
  freemarker:
    charset: UTF-8
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    content-type: text/html
    enabled: true
    suffix: .ftl  #后缀名
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.##
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
    request-context-attribute: req  #req访问request

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: rk.po.po,rk.po.query
  configuration:
    call-setters-on-nulls: true #没有结果则返回null，测试无效
server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:cert/keystore.p12
    key-store-password: Perhaps0..
    key-alias: tomcat
    key-password: Perhaps0..
  servlet:
    session:
      timeout: 12h