

spring:
  redis:
    database: 5
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 3s
    jedis:
      pool:
        max-active: 2000
        max-wait: 1s
        max-idle: 500
        min-idle: 50

    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: "jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf8&useSSL=false"
  freemarker:
    charset: UTF-8
    settings:
      classic_compatible: true
      number_format: 0.##
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd hh:mm:ss

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*.xml
server:
  port: 8080



